service:
  type: LoadBalancer
  loadBalancerIP: 10.0.7.81
persistence:
  enabled: true
  size: 50Gi
  storageClass: nfs-client
resources:
  requests:
    memory: 256Mi
    cpu: 0.1
  limits:
    memory: 2Gi
    cpu: 4
config:
  opentsdb:
    enabled: true
keel:
  policy: all
  trigger: poll
  pollSchedule: "@every 1h"
  images:
    - repository: image.repo
      tag: image.tag
